### ISSUE TITLE
MVP Checklist

### ISSUE THREAD

**Issue by sriumcp** [iter8-tools/iter8-kfserving#61]
- [x] Replace Knative-monitoring
- [ ] Support v1beta1 KFServing APIs in addition to v1alpha2
  - [x] v1alpha2 is auto-converted to v1beta1. So we will focus entirely on v1beta1.
  - [ ] Fix metrics for v1beta1
  - [ ] Readme.md changes
    - [ ] The default and canary models need to be applied in separate steps
    - [ ] Prediction requests need to change
    - [ ] Experiment YAML needs to be checked
    - [ ] Use iter8ctl for watching experiment
- [ ] Integration tests
  - [ ] Test handler functionality
  - [ ] Test failure handling
- [ ] e2e tests that are manually runnable (both these tests leverage some out-of-the-box metrics)
  - [ ] A test for a successful canary release (test using gauge / counters; mean/tail latency / error-rate metrics)
  - [ ] A test for an unsuccessful canary release (test using gauge / counters; mean/tail latency / error-rate metrics)
- [ ] Ensure version pinning
- [ ] Complete documentation

**Comment by sriumcp** [comment]
Done. Moving on to the next release. With support for git-triggered operations.
